import {
  FiActivity,
  FiArrowDown,
  FiArrowLeft,
  FiArrowRight,
  FiAward,
  FiBell,
  FiCalendar,
  FiCamera,
  FiCheck,
  FiChevronDown,
  FiChevronUp,
  FiCopy,
  FiDollarSign,
  FiDownload,
  FiEdit2,
  FiExternalLink,
  FiFilePlus,
  FiHome,
  FiLock,
  FiLogOut,
  FiMenu,
  FiMinus,
  FiMinusCircle,
  FiMoon,
  FiMoreHorizontal,
  FiPlus,
  FiPlusCircle,
  FiSave,
  FiSearch,
  FiSend,
  FiSettings,
  FiShare2,
  FiSlash,
  FiStar,
  FiSun,
  FiThumbsDown,
  FiThumbsUp,
  FiTrash,
  FiUser,
  FiUserPlus,
  FiUsers,
  FiX,
  FiXOctagon,
} from 'react-icons/fi';
import { FaDiscord, FaXTwitter, FaYoutube } from 'react-icons/fa6';
import { MdAddReaction } from 'react-icons/md';

export const ICONS = {
  ActivityIcon: FiActivity,
  AddUserIcon: FiUserPlus,
  ApprovedIcon: FiCheck,
  AddReactionIcon: MdAddReaction,
  BackIcon: FiArrowLeft,
  BellIcon: FiBell,
  CancelIcon: FiSlash,
  ChevronDownIcon: FiChevronDown,
  ChevronUpIcon: FiChevronUp,
  CloseIcon: FiX,
  CopyIcon: FiCopy,
  CreateFineIcon: FiFilePlus,
  CreateScopeIcon: FiUsers,
  DarkModeIcon: FiMoon,
  DateIcon: FiCalendar,
  DeleteIcon: FiTrash,
  DiscordIcon: FaDiscord,
  EditIcon: FiEdit2,
  ExternalLink: FiExternalLink,
  MoreIcon: FiMoreHorizontal,
  HomeIcon: FiHome,
  LightModeIcon: FiSun,
  LockIcon: FiLock,
  MenuIcon: FiMenu,
  MinusIcon: FiMinus,
  MinusCircleIcon: FiMinusCircle,
  PayIcon: FiDollarSign,
  PictureIcon: FiCamera,
  PlusCircleIcon: FiPlusCircle,
  PlusIcon: FiPlus,
  RejectedIcon: FiX,
  ResetIcon: FiTrash,
  SaveIcon: FiSave,
  SearchIcon: FiSearch,
  SendIcon: FiSend,
  SettingsIcon: FiSettings,
  ShareIcon: FiShare2,
  SignOutIcon: FiLogOut,
  StarIcon: FiStar,
  TeamIcon: FiUsers,
  ThumbsDownIcon: FiThumbsDown,
  ThumbsUpIcon: FiThumbsUp,
  TwitterIcon: FaXTwitter,
  UserIcon: FiUser,
  AwardIcon: FiAward,
  DeactivateIcon: FiXOctagon,
  ArrowRightIcon: FiArrowRight,
  YoutubeIcon: FaYoutube,
  DownloadIcon: FiDownload,
  ArrowDownIcon: FiArrowDown
};
