export const NOTIFICATIONS = {
    NOTIFY_USER_OF_NEW_WIN: "NOTIFY_USER_OF_NEW_WIN",
    NOTIFY_USER_OF_NEW_FINE: "NOTIFY_USER_OF_NEW_FINE",
    NOTIFY_SCOPE_OF_NEW_WIN: "NOTIFY_SCOPE_OF_NEW_WIN",
    NOTIFY_SCOPE_OF_NEW_FINE: "NOTIFY_SCOPE_OF_NEW_FINE"
};